import React, { useState } from "react";
import MarketNews from "../components/MarketNews";
import Header from "../components/Header";
import Footer from "../components/Footer";
import FinancialGraph from "../components/FinancialGraph";
import BalanceSheet from "../slices/BalanceSheet";
import CashFlowSheet from "../slices/CashFlowSheet";

interface CompanyScreenProps {
  companyId: string;
}

const CompanyScreen: React.FC<CompanyScreenProps> = ({ companyId }) => {
  const [isExpanded, setIsExpanded] = useState(false);

  const fullText = `International Business Machines Corporation (IBM) is an American
            multinational technology company headquartered in Armonk, New York,
            with operations in over 170 countries. The company began in 1911,
            founded in Endicott, New York, as the Computing-Tabulating-Recording
            Company (CTR) and was renamed International Business Machines in
            1924. IBM is incorporated in New York. IBM produces and sells
            computer hardware, middleware and software, and provides hosting and
            consulting services in areas ranging from mainframe computers to
            nanotechnology. IBM is also a major research organization, holding
            the record for most annual U.S. patents generated by a business (as
            of 2020) for 28 consecutive years. Inventions by IBM include the
            automated teller machine (ATM), the floppy disk, the hard disk
            drive, the magnetic stripe card, the relational database, the SQL
            programming language, the UPC barcode, and dynamic random-access
            memory (DRAM). The IBM mainframe, exemplified by the System/360, was
            the dominant computing platform during the 1960s and 1970s.`;

  const shortText = `${fullText.substring(0, 500)} `;

  return (
    <div>
      <Header name="Guest" />
      <div className="max-w p-4">
        <div className="grid grid-cols-1 md:grid-cols-2 gap-8">
          <div className="col-span-1 space-y-4">
            {/* Company Information */}
            <h1 className="text-3xl font-bold text-gray-800">
              Ticker: {companyId}
            </h1>
            <p className="font-semibold">Asset Type: Common Stock</p>
            <p className="text-gray-600">
              Name: International Business Machines
            </p>
            <p className="text-gray-600">Sector: TECHNOLOGY</p>
            <p className="text-gray-600">
              Industry: COMPUTER & OFFICE EQUIPMENT
            </p>
            <p className="text-gray-600">Country: USA</p>
            {/* Expandable Text */}
            <p className="text-gray-600">Currency: USD</p>
            <p className="text-gray-600">
              {isExpanded ? fullText : shortText}
              {!isExpanded && (
                <span
                  className="text-blue-600 cursor-pointer"
                  onClick={() => setIsExpanded(true)}
                >
                  [...]
                </span>
              )}
            </p>

            <MarketNews
              image1="https://cdn.benzinga.com/files/imagecache/1024x768xUP/images/story/2023/Market-Man-Shutterstock_1.jpeg"
              image2="https://cdn.benzinga.com/files/imagecache/1024x768xUP/images/story/2023/Market-Man-Shutterstock_1.jpeg"
              image3="https://cdn.benzinga.com/files/imagecache/1024x768xUP/images/story/2023/Market-Man-Shutterstock_1.jpeg"
              image4="https://cdn.benzinga.com/files/imagecache/1024x768xUP/images/story/2023/Market-Man-Shutterstock_1.jpeg"
              title="Fed Keeps Rates Steady, …The Week In The Markets"
              timePublished="1 hour ago"
              source="https://markets.businessinsider.com/news/etf/fed-keeps-rates-steady-signals-cuts-for-2024-powell-ignites-stock-rally-the-week-in-the-markets-1032906079"
            />
          </div>
          <div className="col-span-1">
            <FinancialGraph ticker={companyId} />
            <BalanceSheet />
            <CashFlowSheet />
          </div>
        </div>
      </div>
      <Footer />
    </div>
  );
};

export default CompanyScreen;
