import React, { useState } from "react";
import ProfileNews from "../components/ProfileNews";
import Header from "../components/Header";
import Footer from "../components/Footer";
import FinancialGraph from "../components/FinancialGraph";
import BalanceSheet from "../slices/BalanceSheet";
import CashFlowSheet from "../slices/CashFlowSheet";

interface CompanyScreenProps {
  companyId: string;
}

const CompanyScreen: React.FC<CompanyScreenProps> = ({ companyId }) => {
  const [isExpanded, setIsExpanded] = useState(false);

  const fullText = `International Business Machines Corporation (IBM) is an American
            multinational technology company headquartered in Armonk, New York,
            with operations in over 170 countries. The company began in 1911,
            founded in Endicott, New York, as the Computing-Tabulating-Recording
            Company (CTR) and was renamed International Business Machines in
            1924. IBM is incorporated in New York. IBM produces and sells
            computer hardware, middleware and software, and provides hosting and
            consulting services in areas ranging from mainframe computers to
            nanotechnology. IBM is also a major research organization, holding
            the record for most annual U.S. patents generated by a business (as
            of 2020) for 28 consecutive years. Inventions by IBM include the
            automated teller machine (ATM), the floppy disk, the hard disk
            drive, the magnetic stripe card, the relational database, the SQL
            programming language, the UPC barcode, and dynamic random-access
            memory (DRAM). The IBM mainframe, exemplified by the System/360, was
            the dominant computing platform during the 1960s and 1970s.`;

  const shortText = `${fullText.substring(0, 500)} `;

  return (
    <div>
      <Header name="Guest" />
      <div className="max-w p-4">
        <div className="grid grid-cols-1 md:grid-cols-2 gap-8">
          <div className="col-span-1 space-y-4">
            {/* Company Information with Icon */}

            <div className="relative flex items-center space-x-2">
              <h1 className="text-3xl font-bold text-gray-800">
                Ticker: {companyId}
              </h1>
              <div className="relative group">
                <svg
                  onClick={() => console.log("clicked")}
                  xmlns="http://www.w3.org/2000/svg"
                  fill="none"
                  viewBox="0 0 24 24"
                  strokeWidth={2.5}
                  stroke="currentColor"
                  className="w-6 h-6 cursor-pointer transition duration-300 ease-in-out transform group-hover:scale-110"
                >
                  <path
                    strokeLinecap="round"
                    strokeLinejoin="round"
                    d="M12 4.5v15m7.5-7.5h-15"
                  />
                </svg>
                <span className="absolute bottom-full mb-2 hidden group-hover:flex justify-center items-center w-auto min-w-max px-2 py-1 text-xs text-white bg-blue-500 rounded-md shadow-lg transition-all duration-300 ease-in-out opacity-0 group-hover:opacity-100">
                  Add to Wishlist
                </span>
              </div>
            </div>
            {/* End of Company Information with Icon */}

            <p className="font-semibold">Asset Type: Common Stock</p>
            <p className="text-gray-600">
              Name: International Business Machines
            </p>
            <p className="text-gray-600">Sector: TECHNOLOGY</p>
            <p className="text-gray-600">
              Industry: COMPUTER & OFFICE EQUIPMENT
            </p>
            <p className="text-gray-600">Country: USA</p>
            {/* Expandable Text */}
            <p className="text-gray-600">Currency: USD</p>
            <p className="text-gray-600">
              {isExpanded ? fullText : shortText}
              {!isExpanded && (
                <span
                  className="text-blue-600 cursor-pointer"
                  onClick={() => setIsExpanded(true)}
                >
                  [...]
                </span>
              )}
            </p>

            <ProfileNews />
          </div>
          <div className="col-span-1">
            <FinancialGraph ticker={companyId} />
            <BalanceSheet />
            <CashFlowSheet />
          </div>
        </div>
      </div>
      <Footer />
    </div>
  );
};

export default CompanyScreen;
